name: CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -e '.[dev]'
      - name: Lint (ruff/black/isort/mypy)
        run: |
          ruff check .
          black --check .
          isort --check-only .
          mypy packages/poker_core || true
      - name: Tests + Coverage (global 60%, core 80%)
        run: |
          coverage run -m pytest
          coverage report --fail-under=60
          coverage report --include "packages/poker_core/*" --fail-under=80
      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-raw
          path: ./.coverage
